### ISSUE TITLE
Support for vendor pseudo elements

### ISSUE THREAD

**Issue by ooHmartY** [jedmao/postcss-nested-props#3]
Currently vendor pseudo elements are not parsed correctly.

For example using `::-ms-clear`

Expected output (valid css):
```css
input[type=text]::-ms-clear {
    display: none;
}
```

current output (invalid css)
```css
input[type=text]: -ms-clear;
```

This issue is caused by the `HAS_PSEUDO_CLASSES_ELEMENTS` which currently does not account for vendor specific pseudo elements.
